app/__init__.py
from flask import Flask
from .views import views
from celery import Celery


CELERY_TASK_LIST = [
    'app.tasks',
]

def create_celery_app(app=None):
    """
    Create a new Celery object and tie together the Celery config to the app's
    config. Wrap all tasks in the context of the application.
    :param app: Flask app
    :return: Celery app
    """
    app = app or create_app()

    celery = Celery(app.import_name, broker=app.config['CELERY_BROKER_URL'],
                    include=CELERY_TASK_LIST)

    celery.conf.update(app.config)
    celery.conf.result_backend=app.config['CELERY_BROKER_URL']

    TaskBase = celery.Task

    class ContextTask(TaskBase):
        abstract = True

        def __call__(self, *args, **kwargs):
            with app.app_context():
                return TaskBase.__call__(self, *args, **kwargs)

    celery.Task = ContextTask
    return celery


def create_app():
    # Bail if we don't have a market name
    app = Flask(__name__, static_folder='../static')
    app.register_blueprint(views)
    app.config.update({
        'CELERY_BROKER_URL': "redis://redis/0",
    })
    from werkzeug.debug import DebuggedApplication
    app.wsgi_app = DebuggedApplication(app.wsgi_app, True)

    return app

app = create_app()

app/views.py
from flask import Blueprint, render_template, abort, jsonify
from jinja2 import TemplateNotFound

views = Blueprint('views', __name__,
                        template_folder='templates')


@views.route('/', defaults={'page': 'index'})
@views.route('/<page>')
def show(page):
    try:
        return render_template('pages/%s.html' % page)
    except TemplateNotFound:
        abort(404)

@views.route('/send/work')
@views.route('/send/work/')
def send_work():
    from .tasks import test_task

    t = test_task.delay()
    j = jsonify({'task_id': t.id})
    return j


@views.route('/check/work/<tid>', defaults={'is_async': 't'})
@views.route('/check/work/<tid>/<is_async>')
def check_work(tid, is_async):
    from .tasks import celery
    result = celery.AsyncResult(tid)
    print(celery.conf.result_backend)
    if is_async == 't':
        if result.ready():
            # res = repr(result.result).decode("unicode-escape")
            return jsonify({'status':'ready', 'result': result.result})
    else:
        while not result.ready():
            import time
            time.sleep(.5)
        return jsonify({'status':'ready', 'result': result.result})
    return jsonify({'status': 'Not ready'})

app/templates/base.html
<!doctype html>
<title>{% block title %}{% endblock %} - Flask celery JS example</title>
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
<body>
<nav>
  <h1>Flask celery JS example</h1>
</nav>
<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
  {% block content %}{% endblock %}
</section>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="/static/js/app.js"></script>

</body>
</html>

app/templates/pages/index.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Examples{% endblock %}</h1>
{% endblock %}

{% block content %}
  <!-- {% for post in posts %}
    <article class="post">
      <header>
        <div>
          <h1>{{ post['title'] }}</h1>
          <div class="about">by {{ post['username'] }} on {{ post['created'].strftime('%Y-%m-%d') }}</div>
        </div>
        {% if g.user['id'] == post['author_id'] %}
          <a class="action" href="{{ url_for('blog.update', id=post['id']) }}">Edit</a>
        {% endif %}
      </header>
      <p class="body">{{ post['body'] }}</p>
    </article>
    {% if not loop.last %}
      <hr>
    {% endif %}
  {% endfor %} -->
  
  <a class="async" href="{{ url_for('views.send_work') }}">Send a work request</a>
  <br />
  <a class="async" href="{{ url_for('views.send_work') }}">Send a work request</a>
  <br />
  <a class="async" href="{{ url_for('views.send_work') }}">Send a work request</a>
  <br />
  <a class="async" href="{{ url_for('views.send_work') }}">Send a work request</a>
  <br />
  <a class="async" href="{{ url_for('views.send_work') }}">Send a work request</a>
  <br />
  <a class="async" href="{{ url_for('views.send_work') }}">Send a work request</a>
  
{% endblock %}